<!--JQUERY 1.12.1--> 
<script src="../js/jquery-1.12.2.min.js"></script> 
<!--BOOTSTRAP JS--> 
<script src="../js/bootstrap.min.js"></script> 
<!--OWL CAROUSEL--> 
<script src="../js/owl.carousel.min.js"></script> 
<!--SELECT MENU--> 
<script src="../js/jquery.noconflict.js"></script> 
<script src="../js/theme-scripts.js"></script> 
<!--Datepicker js--> 
<script src="../js/zebra_datepicker.js"></script> 
<!--IMAGE MOVING EFFECT--> 
<script src="../js/function.js"></script> 
<!--RUNNING COUNTER--> 
<script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script> 
<script src="../js/jquery.counterup.min.js"></script> 
<!--COUNTER EVENT--> 
<script src="../js/jquery.countdown.min.js"></script> 
<!--CUSTOM JS--> 
<script src="../js/custom.js"></script>
